export const money=n=>new Intl.NumberFormat('en-SG',{style:'currency',currency:'SGD'}).format(n/100);
export function seed(){return {active:'luna',parent:false,children:{luna:{id:'luna',name:'Luna',pet:'Pip',petEmoji:'🐼',level:4,xp:65,jars:{spending:800,savings:4200,giving:600},allowance:'due',goal:{name:'New Bicycle',emoji:'🚲',target:6000},quests:[{id:'q1',name:'Tidy my room',reward:200,status:'ready'},{id:'q2',name:'Help set the table',reward:100,status:'ready'}],unlocks:['🌻','🎀','🧸'],history:[]},maya:{id:'maya',name:'Maya',pet:'Fifi',petEmoji:'🦊',level:3,xp:35,jars:{spending:1100,savings:3100,giving:400},allowance:'due',goal:{name:'Roller Skates',emoji:'🛼',target:5500},quests:[{id:'q3',name:'Pack my school bag',reward:100,status:'ready'}],unlocks:['🌷','🧢'],history:[]}},pending:[],parentBankReconciled:false};}
export function total(c){return c.jars.spending+c.jars.savings+c.jars.giving}
export function requestAllowance(s,id){let c=s.children[id];if(c.allowance!=='due')return false;c.allowance='requested';s.pending.push({id:`a-${id}`,type:'allowance',child:id,label:`${c.name}'s $10 allowance`});return true}
export function approveAllowance(s,id){let p=s.pending.find(x=>x.id===id);if(!p)return false;s.children[p.child].allowance='approved';s.pending=s.pending.filter(x=>x.id!==id);return true}
export function allocate(s,id,split){let c=s.children[id],sum=split.spending+split.savings+split.giving;if(c.allowance!=='approved'||sum!==1000||Object.values(split).some(x=>x<0))return false;for(let k of ['spending','savings','giving'])c.jars[k]+=split[k];c.allowance='complete';c.xp=Math.min(100,c.xp+20);c.history.unshift({icon:'🪙',text:`Split $10 allowance`,at:Date.now()});return true}
export function purchase(s,id,amount,label){let c=s.children[id];if(amount<=0||amount>c.jars.spending)return false;c.jars.spending-=amount;c.history.unshift({icon:'🛍️',text:`Bought ${label} for ${money(amount)}`,at:Date.now()});s.pending.push({id:`p-${Date.now()}`,type:'review',child:id,label:`${c.name}: ${label} ${money(amount)}`});return true}
export function move(s,id,to,amount){let c=s.children[id];if(!['savings','giving'].includes(to)||amount<=0||amount>c.jars.spending)return false;c.jars.spending-=amount;c.jars[to]+=amount;c.xp=Math.min(100,c.xp+5);c.history.unshift({icon:to==='savings'?'✨':'💗',text:`Moved ${money(amount)} to ${to}`,at:Date.now()});return true}
export function submitQuest(s,id,qid){let q=s.children[id].quests.find(x=>x.id===qid);if(!q||q.status!=='ready')return false;q.status='waiting';s.pending.push({id:`q-${qid}`,type:'quest',child:id,qid,label:`${s.children[id].name}: ${q.name}`});return true}
export function approveQuest(s,pid){let p=s.pending.find(x=>x.id===pid);if(!p)return false;let c=s.children[p.child],q=c.quests.find(x=>x.id===p.qid);if(!q)return false;q.status='done';c.jars.spending+=q.reward;c.xp=Math.min(100,c.xp+15);c.history.unshift({icon:'⭐',text:`Quest complete: ${q.name}`,at:Date.now()});s.pending=s.pending.filter(x=>x.id!==pid);return true}
export function parentHeld(s){return Object.values(s.children).reduce((n,c)=>n+c.jars.savings+c.jars.giving,0)}